Bugfix/dsnd 2661
companieshouse/company-links-consumer pull request #114
Opened 2024-06-13 11:17 UTC by SALMANCH007

2024-06-13 13:57 UTC, lbedrosyanCH approved these changes

2024-06-17 15:14 UTC, JAndrewCH requested changes

2024-06-17 15:14 UTC, JAndrewCH commented on src/itest/resources/features/company-links-company-profile-errors.feature
> +  Scenario: Process message when the API returns 409
Test lacks a 'then' step, what are we actually testing here?

2024-06-17 15:14 UTC, JAndrewCH commented on src/itest/resources/features/company-links-company-profile-errors.feature
> +  Scenario: Process message when the API returns 409
I would have thought we would want to confirm that it would not retry and would go the the invalid queue as it should throw a non retryable

2024-06-17 15:14 UTC, JAndrewCH commented on src/itest/java/uk/gov/companieshouse/company/links/config/CucumberContext.java
> +    private static final String RESPONSE = "RESPONSE";
How come we need this now?

2024-06-24 14:40 UTC, JAndrewCH approved these changes

2024-06-24 14:59 UTC, merged