DSND-1896: Upgrade structured logging version
companieshouse/company-links-consumer pull request #87
Opened 2023-07-18 14:01 UTC by johncook-ch

* Added a DataMapHolder class to store a DataMapHolder.Builder instance that captures log data during message processing.
* Added an aspect that wraps around Kafka consumers to initialise the DataMapHolder with message data, then ensures it is clean when processing is complete.
* Updated all logger calls to include the structured logging DataMap content.
* Updated tests that assert log messages to include DataMap content.
* Fixed some linting issues that were breaking the build.

[DSND-1862](https://companieshouse.atlassian.net/browse/DSND-1862)

2023-07-19 16:05 UTC, cgregoryCH requested changes
Looks great, just a couple of missed log lines and a few unused imports

2023-07-19 16:05 UTC, cgregoryCH commented on src/main/java/uk/gov/companieshouse/company/links/service/AppointmentsListClient.java
>                  }
line 74 log is missing logmap

2023-07-19 16:05 UTC, cgregoryCH commented on src/main/java/uk/gov/companieshouse/company/links/service/DeleteExemptionsClient.java
>                  logger.info("HTTP 404 Not Found returned; "
missing logmap

2023-07-19 16:27 UTC, cgregoryCH approved these changes

2023-07-19 16:45 UTC, cgregoryCH submitted a review, later dismissed

2023-07-20 08:59 UTC, sthompsonCH approved these changes

2023-07-20 10:58 UTC, crowlandsCH approved these changes

2023-07-20 14:13 UTC, johncook-ch commented on src/main/java/uk/gov/companieshouse/company/links/logging/MessageLoggingAspect.java
> +                    .orElseGet(() -> "unknown"));
Changed to return a random UUID string instead

2023-07-20 14:43 UTC, cgregoryCH approved these changes

2023-07-20 14:43 UTC, crowlandsCH approved these changes

2023-07-21 07:59 UTC, kinpang-CH approved these changes

2023-07-21 08:29 UTC, merged